fieldLayouts:
  3deedf6c-4cfa-4eab-99ac-c8d63705558d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2c1fd938-132e-4980-8c7c-e7a7d76f7df9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 114600ef-c785-48f9-bab5-460ba83eb9b7
        userCondition: null
handle: singleHome
hasTitleField: true
name: Home
section: 7d923ca0-fc68-4351-98ec-1274de3906db # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
