defaultPlacement: end
enableVersioning: false
handle: singleHome
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fc2cb4bb-e016-46f9-a830-653496da88d7: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/single/home/index
    uriFormat: __home__
type: single
